import argparse
import csv
from pathlib import Path
from typing import Dict, Iterable, List

import cv2

from bounce_rule_detector import (
    BounceCandidate,
    BounceRuleParams,
    detect_bounces,
    load_playable_regions,
    load_track_csv,
    point_in_regions,
)
from eval_bounce_rule import add_common_args, params_from_args


def write_bounces(
    path: str,
    bounces: Iterable[BounceCandidate],
    fps: float,
    playable_regions=None,
) -> None:
    rows: List[Dict[str, object]] = []
    for idx, bounce in enumerate(bounces, 1):
        rows.append(
            {
                "bounce_id": idx,
                "frame_id": bounce.frame_id,
                "time_sec": round(bounce.frame_id / fps, 4) if fps > 0 else "",
                "x": round(bounce.x, 2),
                "y": round(bounce.y, 2),
                "score": round(bounce.score, 3),
                "confidence": round(bounce.confidence, 3),
                "angle_change": round(bounce.angle_change, 3),
                "accel_norm": round(bounce.accel_norm, 3),
                "speed_before": round(bounce.speed_before, 3),
                "speed_after": round(bounce.speed_after, 3),
                "jump_distance": round(bounce.jump_distance, 3),
                "in_ground_region": int(
                    not playable_regions or point_in_regions(bounce.x, bounce.y, playable_regions)
                ),
            }
        )
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as fp:
        fieldnames = [
            "bounce_id",
            "frame_id",
            "time_sec",
            "x",
            "y",
            "score",
            "confidence",
            "angle_change",
            "accel_norm",
            "speed_before",
            "speed_after",
            "jump_distance",
            "in_ground_region",
        ]
        writer = csv.DictWriter(fp, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def draw_bounces(video_path: str, out_path: str, bounces: List[BounceCandidate], codec: str) -> None:
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"failed to open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    writer = cv2.VideoWriter(out_path, cv2.VideoWriter_fourcc(*codec), fps, (width, height))
    if not writer.isOpened():
        raise RuntimeError(f"failed to open video writer: {out_path}")

    by_frame = {b.frame_id: b for b in bounces}
    history: List[BounceCandidate] = []
    frame_id = 0
    while True:
        ok, frame = cap.read()
        if not ok:
            break

        if frame_id in by_frame:
            history.append(by_frame[frame_id])

        for prev in history:
            center = (int(round(prev.x)), int(round(prev.y)))
            cv2.circle(frame, center, 13, (0, 255, 255), 2)
            cv2.circle(frame, center, 3, (0, 255, 255), -1)

        current = by_frame.get(frame_id)
        if current is not None:
            center = (int(round(current.x)), int(round(current.y)))
            cv2.circle(frame, center, 18, (0, 0, 255), 3)
            cv2.putText(
                frame,
                f"Bounce {current.score:.1f}",
                (center[0] + 12, max(24, center[1] - 12)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.7,
                (0, 255, 255),
                2,
                cv2.LINE_AA,
            )

        writer.write(frame)
        frame_id += 1

    cap.release()
    writer.release()


def main() -> None:
    parser = argparse.ArgumentParser(description="Detect tennis bounces from a V3 trajectory CSV.")
    parser.add_argument("--track-csv", required=True, help="CSV with frame_id,x,y,confidence or TrackNet label fields.")
    parser.add_argument("--out-csv", required=True)
    parser.add_argument("--video-path", default="")
    parser.add_argument("--video-out-path", default="")
    parser.add_argument("--court-region-json", default="", help="Playable ground ROI JSON generated by tools/annotate_ground_region.py.")
    parser.add_argument("--fps", type=float, default=30.0)
    parser.add_argument("--codec", default="mp4v")
    add_common_args(parser)
    args = parser.parse_args()

    params: BounceRuleParams = params_from_args(args)
    points = load_track_csv(args.track_csv)
    playable_regions = load_playable_regions(args.court_region_json)
    bounces = detect_bounces(points, params, playable_regions)

    fps = args.fps
    if args.video_path:
        cap = cv2.VideoCapture(args.video_path)
        if cap.isOpened():
            fps = cap.get(cv2.CAP_PROP_FPS) or fps
        cap.release()

    write_bounces(args.out_csv, bounces, fps, playable_regions)
    print(f"bounces = {len(bounces)}")
    print(f"csv     = {args.out_csv}")

    if args.video_path and args.video_out_path:
        draw_bounces(args.video_path, args.video_out_path, bounces, args.codec)
        print(f"video   = {args.video_out_path}")


if __name__ == "__main__":
    main()
